-- MySQL Script generated by MySQL Workbench
-- qua 12 out 2022 18:47:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

CREATE TABLE IF NOT EXISTS `Aluno` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Sexo` CHAR(1) NULL,
  `DataNasc` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Área`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Área` ;

CREATE TABLE IF NOT EXISTS `Área` (
  `Sigla` CHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Área_Sigla` CHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Área_Área1`
    FOREIGN KEY (`Área_Sigla`)
    REFERENCES `Área` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Área_Área1_idx` ON `Área` (`Área_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CURSO` ;

CREATE TABLE IF NOT EXISTS `CURSO` (
  `Sigla` CHAR(3) NOT NULL,
  `Nome` VARCHAR(50) NULL,
  `Horas` INT NULL,
  `Custo` FLOAT NULL,
  `` VARCHAR(50) NULL,
  `Área_Sigla` CHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_CURSO_Área`
    FOREIGN KEY (`Área_Sigla`)
    REFERENCES `Área` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CURSO_Área_idx` ON `CURSO` (`Área_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Matricula` ;

CREATE TABLE IF NOT EXISTS `Matricula` (
  `CURSO_Sigla` CHAR(3) NOT NULL,
  `Aluno_CPF` INT NOT NULL,
  `Data` DATE NULL,
  `Pago` TINYINT NULL,
  PRIMARY KEY (`CURSO_Sigla`, `Aluno_CPF`),
  CONSTRAINT `fk_Matricula_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_CPF`)
    REFERENCES `Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Matricula_Aluno1_idx` ON `Matricula` (`Aluno_CPF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Módulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Módulo` ;

CREATE TABLE IF NOT EXISTS `Módulo` (
  `Sigla` CHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CURSO_Sigla` CHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Módulo_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Módulo_CURSO1_idx` ON `Módulo` (`CURSO_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

CREATE TABLE IF NOT EXISTS `Professor` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CURSO_Sigla` CHAR(3) NOT NULL,
  PRIMARY KEY (`CPF`),
  CONSTRAINT `fk_Professor_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Professor_CURSO1_idx` ON `Professor` (`CURSO_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tópico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tópico` ;

CREATE TABLE IF NOT EXISTS `Tópico` (
  `Sigla` CHAR(3) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Horas` INT NULL,
  `Módulo_Sigla` CHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`, `Módulo_Sigla`),
  CONSTRAINT `fk_Tópico_Módulo1`
    FOREIGN KEY (`Módulo_Sigla`)
    REFERENCES `Módulo` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tópico_Módulo1_idx` ON `Tópico` (`Módulo_Sigla` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
